services:
  api:
    build: ./app
    ports:
      - '8000:8000'
    environment:
      CACHE_HOST: "redis"
      CACHE_PORT: "6379"
      DB_USERNAME: "neojelll"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "mydatabase"
      DB_PASSWORD: "123"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'neojelll'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'mydatabase'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
