name: integration

on:
  push:
    branches:
      - feat/app

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install
      working-directory: app

    - name: Lint with ruff
      run: |
        poetry run ruff formar --check
        poetry run ruff check
      working-directory: app

    - name: Build packages
      run: |
        poetry build
      working-directory: app
